apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: agent
    version: v3.5.11-65b9b59b
  name: agent
  namespace: cloud-agent
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: agent
        version: v3.5.11-65b9b59b
    spec:
      containers:
      - args:
        - /usr/local/bin/docker-entrypoint.sh
        - sleep
        - "600"
        command:
        - /bin/bash
        env:
        - name: direction
        - name: OUTPUT_LOG_PATH
          value: /opt/agent/logs
        - name: isCloud
          value: "true"
        - name: jobTags
          value: asia-east2,-
        - name: cloud_accessCode
          value: ba05e5110884469c94062f88e08a9aee7e6dc0e46d0b42cca3915c5f46b25f99
        - name: backend_url
          value: https://cloud.tapdata.net/console/v3/tm/api/
        - name: version
          value: v3.5.11-65b9b59b
        - name: app_type
          value: DFS
        - name: process_id
          value: 665d7bf12df1a03bfdf51ec6-1hveio9dk
        - name: CONSUMER_SPEED_TOTAL
          value: "0"
        - name: accessKey
          value: ljLT1eaPYxrf2mkaN9N8gCzc7KW6qnke
        - name: secretKey
          value: vdOxdhRHaDIoHqyqEDJ3b49aARnMBIwT
        - name: singletonLock
          value: 665d7b6464c4b4792eaa666c
        #image: asia-docker.pkg.dev/crypto-reality-377106/tapdata/dfs-flow-engine:v3.7.0-665ae5eb
        image: tapdata-docker.pkg.coding.net/dfs/flow-engine/base:0.3
        imagePullPolicy: IfNotPresent
        name: agent
        resources:
          limits:
            cpu: "1"
            memory: "2147483648"
          requests:
            cpu: "1"
            memory: "2147483648"
        securityContext:
          capabilities:
            add:
            - NET_RAW
            - SETPCAP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64