name: Release NTC(network traffic collector)

on:
  push:
    tags:
      - 'v*.*.*'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Library
      run: sudo apt-get install libcurl4-openssl-dev libpcap-dev libssl-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: ntc-${{ runner.os }}-${{ github.ref_name }}
        path: ${{github.workspace}}/build/ntc
        overwrite: true
        compression-level: 9

